ROADMAP = {
    "Python": "Build 2 Python automation/data projects and practice functions, OOP, and testing.",
    "SQL": "Practice joins, CTEs, window functions, subqueries, and analytical SQL.",
    "Statistics": "Study probability, distributions, hypothesis testing, correlation, and regression.",
    "Machine Learning": "Build classification and regression projects and compare multiple algorithms.",
    "Deep Learning": "Learn neural networks, CNNs, training loops, regularization, and transfer learning.",
    "MLOps": "Learn Docker, experiment tracking, model serving, CI/CD, and monitoring.",
    "NLP": "Study tokenization, embeddings, transformers, and text classification.",
    "LLM": "Learn embeddings, RAG, prompt design, evaluation, and retrieval pipelines.",
    "Docker": "Containerize a small ML API and deploy it locally.",
    "Power BI": "Build an interactive dashboard with KPIs, filters, and drill-downs."
}

def generate_roadmap(missing_skills):
    return {skill: ROADMAP.get(skill, f"Learn {skill} through documentation, a guided course, and a practical project.")
            for skill in missing_skills}


def build_action_plan_markdown(target, match_percent, matched_skills, missing_skills):
    matched_skills = sorted(matched_skills)
    missing_skills = sorted(missing_skills)
    required_count = len(matched_skills) + len(missing_skills)
    roadmap = generate_roadmap(missing_skills)

    lines = [
        "# Career action plan",
        "",
        f"**Target role:** {target}",
        f"**Current role alignment:** {match_percent}%",
        f"**Skills recognized:** {len(matched_skills)} of {required_count}",
        "",
        "## How the score works",
        "The score is the percentage of this role's listed skill categories found in the resume. "
        "It is a skills-overlap indicator, not a hiring probability. Role requirements come from "
        "the project's local jobs dataset.",
        "",
        "## Skills already recognized",
    ]

    lines.extend(f"- {skill}" for skill in matched_skills)
    if not matched_skills:
        lines.append("- No listed role skills were recognized yet.")

    lines.extend(["", "## Priority gaps and 30-day plan"])
    if roadmap:
        for index, (skill, action) in enumerate(roadmap.items(), start=1):
            week = min(index, 4)
            first_day = (week - 1) * 7 + 1
            last_day = week * 7 if week < 4 else 28
            lines.extend([
                "",
                f"### Week {week}: {skill} (days {first_day}-{last_day})",
                action,
                f"Deliverable: complete one small, reviewable exercise that demonstrates {skill}.",
            ])
    else:
        lines.extend(["", "No listed skill gaps were found for this role."])

    lines.extend([
        "",
        "### Days 29-30: Bring it together",
        "Publish a small portfolio project that applies the skills above, document your decisions, "
        "and update your resume with the outcome.",
        "",
        "---",
        "Generated by AI Career Navigator. Review the source requirements before making career decisions.",
        "",
    ])
    return "\n".join(lines)
